// ============================================================
//  QUIZ QUESTION BANK - Bhagavad Gita Purushottama Yoga Quiz 3
// ============================================================

const questions = [
  {
    id: 1,
    question: "According to BG 15.12, the sun's splendour that illuminates the entire universe originates from:",
    options: [
      "The sun-god Vivasvān, who is a direct expansion of the Lord",
      "The impersonal brahmajyoti, which is the ultimate source of all light",
      "The Supreme Lord's spiritual effulgence (brahmajyoti emanating from His body)",
      "The combined effulgence of all liberated souls in the spiritual sky"
    ],
    correct: 2
  },
  {
    id: 2,
    question: "According to the purports, what is the fundamental difference between an impersonalist and a devotee regarding the source of light?",
    options: [
      "The impersonalist thinks light comes from the sun; the devotee worships the sun",
      "The impersonalist considers the brahmajyoti the ultimate source, while the devotee knows it is the effulgence of the Lord's body",
      "The impersonalist believes in no source; the devotee believes in many gods",
      "There is no difference; both accept the Lord as the source"
    ],
    correct: 1
  },
  {
    id: 3,
    question: "The Lord enters each planet and supplies the juice of life to all vegetables by becoming:",
    options: [
      "The sun-god Sūrya",
      "The moon-deity Soma",
      "The wind-god Vāyu",
      "The rain-god Indra"
    ],
    correct: 1
  },
  {
    id: 4,
    question: "How do planets remain in their orbits according to BG 15.13?",
    options: [
      "By the universal law of gravitation, which is a manifestation of the Lord's external energy",
      "By the Lord's divine energy alone, which enters each planet and supports it",
      "By the combined efforts of the demigods of the directions",
      "By the centrifugal force generated by the cosmic rotation"
    ],
    correct: 1
  },
  {
    id: 5,
    question: "What is the Sanskrit name for the fire of digestion mentioned in BG 15.14?",
    options: [
      "Sūrya-agni",
      "Jaṭharāgni",
      "Vaiśvānara",
      "Bhūtāgni"
    ],
    correct: 2
  },
  {
    id: 6,
    question: "According to Śrīla Prabhupāda's purport, why is it impossible for a living entity to independently eat and digest?",
    options: [
      "Because the digestive enzymes are insentient and cannot act without conscious direction",
      "Because the Lord must personally help as the fire of digestion in every body",
      "Because the food must first be offered to the Lord with devotion",
      "Because the mind must be in a perfectly peaceful state for proper digestion"
    ],
    correct: 1
  },
  {
    id: 7,
    question: "The Lord says He is celebrated both in the world and in the Vedas as:",
    options: [
      "Parameśvara",
      "Puruṣottama",
      "Sarveśvara",
      "Mahāpuruṣa"
    ],
    correct: 1
  },
  {
    id: 8,
    question: "The Lord gives remembrance, knowledge and forgetfulness from which specific location?",
    options: [
      "From the vast sky",
      "From the Vedic hymns themselves",
      "From the heart of all living beings (as the Supersoul)",
      "From the sun globe"
    ],
    correct: 2
  },
  {
    id: 9,
    question: "According to the purport of verse 15, how does the Supersoul deal with a living entity who wants to enjoy material life?",
    options: [
      "He immediately punishes them to rectify their desires",
      "He gives them complete remembrance of God so they can choose",
      "He causes them to forget the Lord and their spiritual identity",
      "He forces them to take sannyāsa to purify themselves"
    ],
    correct: 2
  },
  {
    id: 10,
    question: "The Lord says, 'vedaiś ca sarvair aham eva vedyaḥ.' What does this mean?",
    options: [
      "I am to be known by all the Vedas",
      "All the Vedas are to be known only by Me",
      "I alone know the real meaning of all the Vedas",
      "The Vedas are meant exclusively for My worship"
    ],
    correct: 0
  },
  {
    id: 11,
    question: "What two titles related to the Vedas does the Lord claim in verse 15.15?",
    options: [
      "Vedānta-sūtra-kartā and Veda-vaktā",
      "Vedānta-kṛt and Veda-vit",
      "Veda-pravaktā and Veda-guhya-vit",
      "Vedānta-guhya and Veda-nirṇetā"
    ],
    correct: 1
  },
  {
    id: 12,
    question: "Why does Śrīla Prabhupāda stress that the Lord is 'Veda-vit' (knower of the Vedas)?",
    options: [
      "To show that devotees must memorize all the Vedas",
      "To prove that the Vedas are unknown to the Lord",
      "To establish the Lord as the ultimate authority on the Vedas, and that knowing Him is the real purpose of all Vedic study",
      "To encourage academic study of the Vedas"
    ],
    correct: 2
  },
  {
    id: 13,
    question: "What does the word 'kūṭasthaḥ' refer to, and what is its literal meaning?",
    options: [
      "The kṣara souls; 'those who are fragmented'",
      "The akṣara souls; 'one who is situated on an anvil,' meaning unchanging",
      "The Supreme Lord; 'the foundation of everything'",
      "The material world; 'a temporary platform'"
    ],
    correct: 1
  },
  {
    id: 14,
    question: "According to the purport to verse 16, which statement about akṣara (infallible) living entities is correct?",
    options: [
      "They are souls who attained liberation after many births in the material world",
      "They are eternally situated in the spiritual world and never come in contact with matter",
      "They are the particles of the impersonal brahmajyoti",
      "They are the demigods who control universal affairs"
    ],
    correct: 1
  },
  {
    id: 15,
    question: "What is the prescribed process to cleanse the weakness of the heart and understand the sublime message of Bhagavad-gītā?",
    options: [
      "Study of Vedānta-sūtra",
      "Performance of severe austerities",
      "Chanting of the Hare Kṛṣṇa mahā-mantra",
      "Association with pure devotees without fail"
    ],
    correct: 2
  },
  {
    id: 16,
    question: "Verse 17 introduces the Supreme Person as 'uttamaḥ puruṣaḥ … paramātmety udāhṛtaḥ.' This means He is known as:",
    options: [
      "Paramātmā (the Supreme Soul)",
      "Virāṭ-rūpa (the universal form)",
      "Para-brahman (the Supreme Brahman)",
      "Ādi-puruṣa (the original person)"
    ],
    correct: 0
  },
  {
    id: 17,
    question: "Śrīla Prabhupāda emphasizes that the Lord is known as Paramātmā because He pervades the entire universe. How does this differ from the individual soul?",
    options: [
      "The individual soul can also pervade the universe after liberation",
      "The individual soul is atomic and localized, and therefore cannot pervade; only the Lord can",
      "The individual soul is ultimately the same as the Paramātmā",
      "The individual soul becomes Paramātmā through perfect yoga"
    ],
    correct: 1
  },
  {
    id: 18,
    question: "The purport to verse 14 explains that the Vaiśvānara fire is an expansion of the Supreme Lord. What devotional conclusion does Śrīla Prabhupāda draw from this?",
    options: [
      "Eating is a purely biological process",
      "Every act of eating is an opportunity to remember God's mercy, as He is directly digesting our food",
      "We should eat as much as possible to satisfy the Lord within",
      "Only food offered as prasādam can be digested by the Lord"
    ],
    correct: 1
  },
  {
    id: 19,
    question: "Which of the following best represents the essence of BG 15.18 as explained by Śrīla Prabhupāda?",
    options: [
      "The Lord is equal to the liberated souls in all respects",
      "The Lord is the supreme ruler of only the material world",
      "The Lord is qualitatively one with, but quantitatively superior to, all living entities",
      "The Lord is transcendental to both conditioned and liberated souls, and is celebrated as Puruṣottama"
    ],
    correct: 3
  },
  {
    id: 20,
    question: "What does one who knows Kṛṣṇa as Puruṣottama without doubt become?",
    options: [
      "A philosopher of the highest order",
      "A knower of everything and a devotee who serves with all his being",
      "A mystic yogī endowed with all siddhis",
      "The ruler of the universe"
    ],
    correct: 1
  },
  {
    id: 21,
    question: "What is the Sanskrit phrase used for one who 'engages in devotional service with all his being'?",
    options: [
      "sarva-dharmān parityajya",
      "bhajati māṁ sarva-bhāvena",
      "man-manā bhava mad-bhakto",
      "satataṁ kīrtayanto mām"
    ],
    correct: 1
  },
  {
    id: 22,
    question: "Kṛṣṇa calls this teaching the 'most confidential part of the scriptures.' The Sanskrit compound word used is:",
    options: [
      "guhyam",
      "guhyatamam",
      "guhya-guhyam",
      "ati-guhyam"
    ],
    correct: 1
  },
  {
    id: 23,
    question: "What are the two results for one who understands this most confidential knowledge, as mentioned in the last line of verse 20?",
    options: [
      "Wealth and fame",
      "Mokṣa and svarga",
      "Buddhimān (wise) and kṛta-kṛtya (all duties perfected)",
      "Peace and prosperity"
    ],
    correct: 2
  },
  {
    id: 24,
    question: "In the purport to BG 15.20, Śrīla Prabhupāda explains that materialistic persons cannot understand that the Supreme Lord is the enjoyer of everything because of:",
    options: [
      "Lack of Vedic education",
      "Weakness of their hearts (hṛdaya-daurbalya)",
      "Influence of the mode of ignorance",
      "Their impersonal philosophical background"
    ],
    correct: 1
  },
  {
    id: 25,
    question: "What distinguishes kṣara living entities according to the purport of verse 16?",
    options: [
      "They are eternally conditioned and can never attain liberation",
      "They struggle due to contact with matter and the threefold miseries",
      "They are impersonalists by nature",
      "They have no individual identity"
    ],
    correct: 1
  }
];

module.exports = questions;